apiVersion: apps/v1
kind: Deployment
metadata:
  name: easeai-deployment
  labels:
    app: easeai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: easeai
  template:
    metadata:
      labels:
        app: easeai
    spec:
      containers:
        - name: easeai-container
          image: harshitrai20/easeai:latest
          imagePullPolicy: Never  # <-- changed
          ports:
            - containerPort: 5000
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: PYTHONPATH
              value: /app/App
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: easeai-service
  labels:
    app: easeai
spec:
  type: NodePort
  selector:
    app: easeai
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
