global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  
  - job_name: 'signease-ai-app'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app]
        action: keep
        regex: signease-ai  
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        action: keep
        regex: http  
